/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/InfoChip copy.vue')['default']
    CountItem: typeof import('./components/CountItem.vue')['default']
    ExtraInfoChip: typeof import('./components/ExtraInfoChip.vue')['default']
    ExtraSingle: typeof import('./components/ExtraSingle.vue')['default']
    InfoChip: typeof import('./components/InfoChip.vue')['default']
    MainCounts: typeof import('./components/MainCounts.vue')['default']
    MainInfo: typeof import('./components/MainInfo.vue')['default']
    MainRank: typeof import('./components/MainRank.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploaderInfo: typeof import('./components/UploaderInfo.vue')['default']
  }
}
