/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    BackgroundIcons: typeof import('./components/BackgroundIcons.vue')['default']
    BackgroundImage: typeof import('./components/BackgroundImage.vue')['default']
    CalenSingle: typeof import('./components/CalenSingle.vue')['default']
    copy: typeof import('./components/BackgroundImage copy.vue')['default']
    CountItem: typeof import('./components/CountItem.vue')['default']
    ExtraList: typeof import('./components/ExtraList.vue')['default']
    ExtraSingle: typeof import('./components/ExtraSingle.vue')['default']
    GuanZhongInfo: typeof import('./components/GuanZhongInfo.vue')['default']
    InfoChip: typeof import('./components/InfoChip.vue')['default']
    MainCounts: typeof import('./components/MainCounts.vue')['default']
    MainInfo: typeof import('./components/MainInfo.vue')['default']
    MainRank: typeof import('./components/MainRank.vue')['default']
    PickInfo: typeof import('./components/PickInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideInfoChip: typeof import('./components/SideInfoChip.vue')['default']
    SideUploaderInfo: typeof import('./components/SideUploaderInfo.vue')['default']
    StaffBox: typeof import('./components/StaffBox.vue')['default']
    TransitionImage: typeof import('./components/TransitionImage.vue')['default']
    UploaderInfo: typeof import('./components/UploaderInfo.vue')['default']
  }
}
